"""allow larger log write

Revision ID: 04cbaa599733
Revises: c591cdedf747
Create Date: 2022-10-13 14:07:37.277413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04cbaa599733"
down_revision = "c591cdedf747"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("log", schema=None) as batch_op:
        batch_op.alter_column(
            "json_data",
            existing_type=sa.VARCHAR(length=1000),
            type_=sa.String(length=2500),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("log", schema=None) as batch_op:
        batch_op.alter_column(
            "json_data",
            existing_type=sa.String(length=2500),
            type_=sa.VARCHAR(length=1000),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
