"""add created_at to course, registration objects

Revision ID: 62d8c47d4959
Revises: c7a322832ad4
Create Date: 2021-06-18 13:35:02.181881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d8c47d4959'
down_revision = 'c7a322832ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('course_user_attended', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_user_attended', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
