"""update linked table name

Revision ID: 66cbfcca0efa
Revises: 3423705349bc
Create Date: 2021-05-26 12:08:32.671680

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '66cbfcca0efa'
down_revision = '3423705349bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_user_attended',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_user_attended')
    # ### end Alembic commands ###
