"""course accommodation table

Revision ID: c591cdedf747
Revises: 62d8c47d4959
Create Date: 2022-03-22 10:57:38.347865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c591cdedf747'
down_revision = '62d8c47d4959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_accommodation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=1500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_accommodations',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['user_accommodation.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'accommodation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_accommodations')
    op.drop_table('user_accommodation')
    # ### end Alembic commands ###
